# Тестовое задание на позицию Cпециалист-аналитик

### Задание 1. Реестр

С помощью скрипта на python преобразовать исходные данные до датафрейма требуемого формата (ожидаемый результат представлен на листе «Вывод»)

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Считываем исходные данные
# Для удобства проверки задания и возможности прогона скрипта зальём датасеты на Google.Drive.
url = 'https://docs.google.com/spreadsheets/d/1H-FIBAiCiBCFVlBwCBo4WGQjXsUEnQd_/edit?usp=share_link&ouid=104521593033447016990&rtpof=true&sd=true'
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
initial_data = pd.read_excel(path, sheet_name=0)

In [3]:
initial_data

,№,Диагноз,Код \nуслуги,Название услуги,Unnamed: 4,Unnamed: 5,Цена по прейскуранту,Цена со скидкой,Кол-\nво,Сумма со скидкой
0,Иванов Иван Иванович Полис...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,13.07.2022,NaN,Врач Горелов,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,H52.0,1.2.4,"Прием (осмотр, консультация) врача-ревматоло...",NaN,NaN,1112.0,1112.0,1.0,1112.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,14.07.2022,NaN,Врач Аксенов,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,J30.0 J34.2 K21 H91.1,1.31.1,"Прием (осмотр, консультация) врача-терапевта...",NaN,NaN,1112.0,1112.0,1.0,1112.0
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Петров Петр Петрович Полис № 23-555555/27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,19.07.2022,NaN,Врач Щедрин,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,M54.2 M54.6 M54.1,1.8.1,"Прием (осмотр, консультация) врача-пульмонол...",NaN,NaN,1073.0,1073.0,1.0,1073.0

In [4]:
# Посмотрим типы данных
initial_data.dtypes

№                        object
Диагноз                  object
Код \nуслуги             object
Название услуги          object
Unnamed: 4              float64
Unnamed: 5              float64
Цена по прейскуранту    float64
Цена со скидкой         float64
Кол-\nво                float64
Сумма со скидкой        float64
dtype: object

In [5]:
# Считываем данные и отображаем ожидаемый результат
output_data = pd.read_excel(path, sheet_name=1)

In [6]:
output_data

,ФИО,Номер полиса,Дата оказания услуги,Код услуги,Диагноз,Наименование услуги,Кол-во,Цена по прейскуранту,Сумма со скидкой
0,Иванов Иван Иванович,23-555555/10,13.07.2022,1.2.4,H52.0,"Прием (осмотр, консультация) врача-ревматоло...",1,1112,1112
1,Иванов Иван Иванович,23-555555/10,14.07.2022,1.31.1,J30.0 J34.2 K21 H91.1,"Прием (осмотр, консультация) врача-терапевта...",1,1112,1112
2,Петров Петр Петрович,23-555555/27,19.07.2022,1.8.1,M54.2 M54.6 M54.1,"Прием (осмотр, консультация) врача-пульмонол...",1,1073,1073

In [7]:
# Посмотрим типы данных
output_data.dtypes

ФИО                     object
Номер полиса            object
Дата оказания услуги    object
Код услуги              object
Диагноз                 object
Наименование услуги     object
Кол-во                   int64
Цена по прейскуранту     int64
Сумма со скидкой         int64
dtype: object

### Решение

In [8]:
# 1. Убираем записи, состоящие целиком из NAN значений, т.к. маловероятно, что они нам пригодятся.
df = initial_data.dropna(how='all')

In [9]:
# 2. Имеются столбцы, состоящие целиком из NAN значений. Удалим их, чтобы не мозолили глаз.
df = df.dropna(axis=1, how='all')

In [10]:
df

,№,Диагноз,Код \nуслуги,Название услуги,Цена по прейскуранту,Цена со скидкой,Кол-\nво,Сумма со скидкой
0,Иванов Иван Иванович Полис...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,13.07.2022,NaN,Врач Горелов,NaN,NaN,NaN,NaN
2,NaN,H52.0,1.2.4,"Прием (осмотр, консультация) врача-ревматоло...",1112.0,1112.0,1.0,1112.0
5,NaN,14.07.2022,NaN,Врач Аксенов,NaN,NaN,NaN,NaN
6,NaN,J30.0 J34.2 K21 H91.1,1.31.1,"Прием (осмотр, консультация) врача-терапевта...",1112.0,1112.0,1.0,1112.0
10,Петров Петр Петрович Полис № 23-555555/27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,19.07.2022,NaN,Врач Щедрин,NaN,NaN,NaN,NaN
12,NaN,M54.2 M54.6 M54.1,1.8.1,"Прием (осмотр, консультация) врача-пульмонол...",1073.0,1073.0,1.0,1073.0

In [11]:
# 3. Для удобства переименуем колонки
df = df.rename(columns={'№': 'fio', 
                   'Диагноз': 'diagnosis', 
                   'Код \nуслуги': 'service_code', 
                   'Название услуги': 'tittle', 
                   'Цена по прейскуранту': 'price', 
                   'Цена со скидкой': 'discounted_price',
                   'Кол-\nво': 'quantity',
                   'Сумма со скидкой': 'discounted_sum'})

In [12]:
# 4. Создадим колонку 'Номер полиса' ('policy_number')
df['policy_number'] = df.fio

In [13]:
df

,fio,diagnosis,service_code,tittle,price,discounted_price,quantity,discounted_sum,policy_number
0,Иванов Иван Иванович Полис...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Иванов Иван Иванович Полис...
1,NaN,13.07.2022,NaN,Врач Горелов,NaN,NaN,NaN,NaN,NaN
2,NaN,H52.0,1.2.4,"Прием (осмотр, консультация) врача-ревматоло...",1112.0,1112.0,1.0,1112.0,NaN
5,NaN,14.07.2022,NaN,Врач Аксенов,NaN,NaN,NaN,NaN,NaN
6,NaN,J30.0 J34.2 K21 H91.1,1.31.1,"Прием (осмотр, консультация) врача-терапевта...",1112.0,1112.0,1.0,1112.0,NaN
10,Петров Петр Петрович Полис № 23-555555/27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Петров Петр Петрович Полис № 23-555555/27
11,NaN,19.07.2022,NaN,Врач Щедрин,NaN,NaN,NaN,NaN,NaN
12,NaN,M54.2 M54.6 M54.1,1.8.1,"Прием (осмотр, консультация) врача-пульмонол...",1073.0,1073.0,1.0,1073.0,NaN

In [14]:
# 5. Займёмся атрибутом ФИО (fio)
# Создадим функцию split_fio, которая отбирает элементы [0:3] от строки (fio) и объединяет их.
def split_fio(fio):
    return ' '.join(str(fio).split(' ')[0:3])

In [15]:
df['fio'] = df.fio.apply(split_fio)

In [16]:
# 6. По аналогии поступим и созданным полем 'policy_number'
def split_policy_number (policy_number):
    return str(policy_number).split(' ')[-1]

In [17]:
df['policy_number'] = df.policy_number.apply(split_policy_number)

In [18]:
df

,fio,diagnosis,service_code,tittle,price,discounted_price,quantity,discounted_sum,policy_number
0,Иванов Иван Иванович,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23-555555/10
1,nan,13.07.2022,NaN,Врач Горелов,NaN,NaN,NaN,NaN,nan
2,nan,H52.0,1.2.4,"Прием (осмотр, консультация) врача-ревматоло...",1112.0,1112.0,1.0,1112.0,nan
5,nan,14.07.2022,NaN,Врач Аксенов,NaN,NaN,NaN,NaN,nan
6,nan,J30.0 J34.2 K21 H91.1,1.31.1,"Прием (осмотр, консультация) врача-терапевта...",1112.0,1112.0,1.0,1112.0,nan
10,Петров Петр Петрович,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23-555555/27
11,nan,19.07.2022,NaN,Врач Щедрин,NaN,NaN,NaN,NaN,nan
12,nan,M54.2 M54.6 M54.1,1.8.1,"Прием (осмотр, консультация) врача-пульмонол...",1073.0,1073.0,1.0,1073.0,nan

In [19]:
# 7. Создадим пустую колонку 'Дата оказания услуги' (date). 
# Данный шаг совсем не обязателен и может быть пропущен, однако с ним визуально проще сравнивать нашу таблицу с ожидаемым результатом. 
df['date'] = np.nan

In [20]:
df.columns

Index(['fio', 'diagnosis', 'service_code', 'tittle', 'price',
       'discounted_price', 'quantity', 'discounted_sum', 'policy_number',
       'date'],
      dtype='object')

In [21]:
# Расположим столбцы в требуемом порядке и обновим индексы.
order_of_columns = ['fio', 'policy_number', 'date', 'service_code', 'diagnosis', 'tittle', 'quantity', 'price', 'discounted_sum']
df = df[order_of_columns]
df = df.reset_index(drop=True)
df

,fio,policy_number,date,service_code,diagnosis,tittle,quantity,price,discounted_sum
0,Иванов Иван Иванович,23-555555/10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,nan,nan,NaN,NaN,13.07.2022,Врач Горелов,NaN,NaN,NaN
2,nan,nan,NaN,1.2.4,H52.0,"Прием (осмотр, консультация) врача-ревматоло...",1.0,1112.0,1112.0
3,nan,nan,NaN,NaN,14.07.2022,Врач Аксенов,NaN,NaN,NaN
4,nan,nan,NaN,1.31.1,J30.0 J34.2 K21 H91.1,"Прием (осмотр, консультация) врача-терапевта...",1.0,1112.0,1112.0
5,Петров Петр Петрович,23-555555/27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,nan,nan,NaN,NaN,19.07.2022,Врач Щедрин,NaN,NaN,NaN
7,nan,nan,NaN,1.8.1,M54.2 M54.6 M54.1,"Прием (осмотр, консультация) врача-пульмонол...",1.0,1073.0,1073.0

In [22]:
# Посмотрим на первое значение столбца fio.
df.fio.iloc[0]

'Иванов Иван Иванович'

In [23]:
# 8. Составим цикл для замены 'nan' на полные ФИО. 
# Плюс такого подхода в том, что он будет работать при изменении количества записей и их последовательности. 
# Минус - скорость работы на больших данных.
names = []
x = 0
n = 0
for i in df.fio: 
    if i != 'nan' and i == df.fio.iloc[x]:
        n += 1
        names.append(i)
    elif i == 'nan':
        i = df.fio.iloc[x]
        n += 1
        names.append(i)
    elif i != 'nan':
        x = n
        i = df.fio.iloc[x]
        n += 1
        names.append(i)

df['fio'] = names

In [24]:
# 9. Аналогично поступим с policy_number

pls_numbers = []
x = 0
n = 0
for i in df.policy_number: 
    if i != 'nan' and i == df.policy_number.iloc[x]:
        n += 1
        pls_numbers.append(i)
    elif i == 'nan':
        i = df.policy_number.iloc[x]
        n += 1
        pls_numbers.append(i)
    elif i != 'nan':
        x = n
        i = df.policy_number.iloc[x]
        n += 1
        pls_numbers.append(i)

df['policy_number'] = pls_numbers

In [25]:
df

,fio,policy_number,date,service_code,diagnosis,tittle,quantity,price,discounted_sum
0,Иванов Иван Иванович,23-555555/10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Иванов Иван Иванович,23-555555/10,NaN,NaN,13.07.2022,Врач Горелов,NaN,NaN,NaN
2,Иванов Иван Иванович,23-555555/10,NaN,1.2.4,H52.0,"Прием (осмотр, консультация) врача-ревматоло...",1.0,1112.0,1112.0
3,Иванов Иван Иванович,23-555555/10,NaN,NaN,14.07.2022,Врач Аксенов,NaN,NaN,NaN
4,Иванов Иван Иванович,23-555555/10,NaN,1.31.1,J30.0 J34.2 K21 H91.1,"Прием (осмотр, консультация) врача-терапевта...",1.0,1112.0,1112.0
5,Петров Петр Петрович,23-555555/27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Петров Петр Петрович,23-555555/27,NaN,NaN,19.07.2022,Врач Щедрин,NaN,NaN,NaN
7,Петров Петр Петрович,23-555555/27,NaN,1.8.1,M54.2 M54.6 M54.1,"Прием (осмотр, консультация) врача-пульмонол...",1.0,1073.0,1073.0

In [26]:
# 10. Из вышеприведённой таблицы видно, что местоположение даты имеет закономерность. Она выше названия услуги на 1 строку.
# Заполним колонку 'date' с соответствующим смещением.
df['date'] = df.diagnosis.shift(1)
#df

In [27]:
# 11. Удалим все строки, имеющие хотя бы одно NAN.
df = df.dropna()
df

,fio,policy_number,date,service_code,diagnosis,tittle,quantity,price,discounted_sum
2,Иванов Иван Иванович,23-555555/10,13.07.2022,1.2.4,H52.0,"Прием (осмотр, консультация) врача-ревматоло...",1.0,1112.0,1112.0
4,Иванов Иван Иванович,23-555555/10,14.07.2022,1.31.1,J30.0 J34.2 K21 H91.1,"Прием (осмотр, консультация) врача-терапевта...",1.0,1112.0,1112.0
7,Петров Петр Петрович,23-555555/27,19.07.2022,1.8.1,M54.2 M54.6 M54.1,"Прием (осмотр, консультация) врача-пульмонол...",1.0,1073.0,1073.0

In [28]:
# 12. Обновим индекс
df = df.reset_index(drop=True)

In [29]:
# 13. Приведём 3 последних столбца к требуемому виду.
df.price = df.price.astype(int)
df.discounted_sum = df.discounted_sum.astype(int)
df.quantity = df.quantity.astype(int)

In [30]:
df

,fio,policy_number,date,service_code,diagnosis,tittle,quantity,price,discounted_sum
0,Иванов Иван Иванович,23-555555/10,13.07.2022,1.2.4,H52.0,"Прием (осмотр, консультация) врача-ревматоло...",1,1112,1112
1,Иванов Иван Иванович,23-555555/10,14.07.2022,1.31.1,J30.0 J34.2 K21 H91.1,"Прием (осмотр, консультация) врача-терапевта...",1,1112,1112
2,Петров Петр Петрович,23-555555/27,19.07.2022,1.8.1,M54.2 M54.6 M54.1,"Прием (осмотр, консультация) врача-пульмонол...",1,1073,1073

In [31]:
# 14. Финальное переименование
df = df.rename(columns={'fio': 'ФИО', 
                   'policy_number': 'Номер полиса', 
                   'date': 'Дата оказания услуг', 
                   'service_code': 'Код услуги', 
                   'diagnosis': 'Диагноз', 
                   'tittle': 'Наименование услуги',
                   'quantity': 'Кол-во',
                   'price': 'Цена по прейскуранту', 
                   'discounted_sum': 'Сумма со скидкой'})

In [32]:
# Результат
df

,ФИО,Номер полиса,Дата оказания услуг,Код услуги,Диагноз,Наименование услуги,Кол-во,Цена по прейскуранту,Сумма со скидкой
0,Иванов Иван Иванович,23-555555/10,13.07.2022,1.2.4,H52.0,"Прием (осмотр, консультация) врача-ревматоло...",1,1112,1112
1,Иванов Иван Иванович,23-555555/10,14.07.2022,1.31.1,J30.0 J34.2 K21 H91.1,"Прием (осмотр, консультация) врача-терапевта...",1,1112,1112
2,Петров Петр Петрович,23-555555/27,19.07.2022,1.8.1,M54.2 M54.6 M54.1,"Прием (осмотр, консультация) врача-пульмонол...",1,1073,1073

----------------------------------------------------------------------------------------------------------------------

### Задание 2. Города_vba

С помощью макроса vba обработать данные на листе «Адреса» таким образом (ожидаемый результат представлен на листе «Вывод»):

* если один из городов на листе «Города» указан в адресе, в соседней ячейке следует указать найденный город;

* если ни один из городов на листе «Города» в адресе не найден, соседняя ячейка должна остаться пустой.

Если результат не получится с помощью макроса – можно использовать скрипт на python.

### Решение

In [33]:
# Файл '2023_04_02_Сасимович_И.С. (решение_задания_2_город_vba).xlsm' прилагается.
# Также он доступен по ссылке, хранящейся в переменной URL, находящейся в ячейке с кодом ниже.

Option Compare Text

Sub FindCity()

    Dim cities As Range
    Dim cell As Range
    Dim lastRow As Long
    Dim i As Long
    Dim patern As String
    
    Set cities = ThisWorkbook.Worksheets(1).Range("a2", ThisWorkbook.Worksheets(1).Range("a2").End(xlDown))

    lastRow = ThisWorkbook.Worksheets(2).Cells(Rows.Count, 1).End(xlUp).Row
    
    For i = 2 To lastRow
        For Each cell In cities
            patern = "*" & cell & ",*"
            If ThisWorkbook.Worksheets(2).Cells(i, 1).Value Like patern Then
            ThisWorkbook.Worksheets(2).Cells(i, 2) = cell.Value
    Exit For
            End If
        Next cell
    Next i

End Sub

In [34]:
# Результат выполнения макроса FindCity
url = 'https://docs.google.com/spreadsheets/d/13Vxjdd5CU7WLed8uJLMZ9U9FCzMoenWr/edit?usp=share_link&ouid=104521593033447016990&rtpof=true&sd=true'
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
result = pd.read_excel(path, sheet_name=1)
result

                                            Адреса   Unnamed: 1
0                 г. Москва, ул. Пятницкая, дом 33       Москва
1  г. Москва, Ленинский проспект, дом 11, корпус 3       Москва
2            г новосибирск, улица дорожная, дом 44  Новосибирск
3       г.казань, ул. Хадии Давлетшиной, дом 55/45       Казань
4              г. Тула, улица Новосибирская, дом 6          NaN
5    г. Петрозаводск, ул. Невзора, дом 6, корпус 4          NaN